service: dynamodb-rust-demo
provider:
  name: aws
  runtime: rust
  memorySize: 128
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
      Resource:
        - "arn:aws:dynamodb:ap-northeast-1:*:table/Pets"
package:
  individually: true
 
plugins:
  - serverless-rust
 
functions:
  dynamodb-crud-demo:
    handler: dynamodb-crud-demo